### ISSUE TITLE
[Bug] 문제 카테고리 누락

### ISSUE THREAD

**Issue by sehwanii** [CAU-MobileAppDev-2024-Team22/DailyCS#11]
## 🐞 버그 설명 (Bug Description)
- QuestionListPage 에서 문제 카테고리가 누락되어 표시되지 않습니다.

## 📷 스크린샷 (Screenshots)
<img width="203" alt="image" src="https://github.com/user-attachments/assets/1704ec6f-71fb-4f67-a61d-3b3479d68cd8">

**Comment by dev-joeysos** [comment]
<img src="https://github.com/user-attachments/assets/40a0f5b8-b5d8-45f6-ac56-54dad24c6e5f" alt="Screenshot" width="200">

해결완료
